### ISSUE TITLE
전표처리-전표입력 2. 출금전표 tab키 이동 안됨.

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#233]
메뉴: 전표처리-전표입력 2. 출금전표
증상 : 아래 이미지에서 보는 바와 같이, tab 키도 다음 셀로 이동하려 해도 후원자명 셀에 갇혀서 다음 셀일 적요로 이동하지 않음.

개선요망 : 후원자명 셀에서 tab 키 입력시 적요 칸으로 이동

<img width="1024" height="802" alt="Image" src="https://github.com/user-attachments/assets/2b4730b8-61fd-4a12-8cad-e5b4f6a87169" />

**Comment by tienemctai** [comment]
Fixed in v0.0.92.

**Comment by boazseong** [comment]
Not it is not fixed yet. 

https://github.com/user-attachments/assets/2ec651e1-e34b-4935-89c2-19098dce8604

**Comment by tienemctai** [comment]
Yes, I understood. 
I thought it should move to the next cell with a tab key only when the "Sponsor Name" cell is not empty.
So I'll fix it to move the next cell even if that cell is empty. Thanks.

**Comment by tienemctai** [comment]
Please tell me what is the warning message (in English)?

**Comment by tienemctai** [comment]
I could run installing the file well on my machine without any warning.

<img width="945" height="237" alt="Image" src="https://github.com/user-attachments/assets/e394a6fe-850f-40c8-aa1c-4337d5209e32" />

**Comment by tienemctai** [comment]
So let me try releasing a new version.

**Comment by tienemctai** [comment]
Please try again with v0.0.95
